### ISSUE TITLE
Add support for injecting components into translations

### ISSUE THREAD

**Issue by L1lith** [Avansai/next-multilingual#19]
The problem with the current text interpolation is that it's forced into plaintext, and doesn't support components. This is an issue for me because I often have links or other tags in the middle of a paragraph of text. You can see it here:
https://yourfirstrpg.com/vision

compiled html
```
just read the <a>docs<a> ... text continued
```
But this ends up making an extra 2 translation segments for every link, one for the link and one for the text continuation 
In one of the worst cases, my translation page ended up looking like this because of how many links there were (I have a bunch of links because the text has hoverable definitions)
```
yFRPG.logicModels.decisionTableLabelOne = Input
yFRPG.logicModels.decisionTableLabelTwo = Output
yFRPG.logicModels.decisionTableInputOne = Light is red
yFRPG.logicModels.decisionTableOutputOne = Come to a smooth stop before the intersection.
yFRPG.logicModels.decisionTableInputTwo = Light is yellow
yFRPG.logicModels.decisionTableOutputTwo = Pay attention to the intersection. If you can stop, stop quickly.
yFRPG.logicModels.decisionTableInputThree = Light is green
yFRPG.logicModels.decisionTableOutputThree = Look ahead to ensure the traffic is clear, and continue on.
yFRPG.logicModels.codingPartOne = In coding we have a set of software and methodology that makes describing our logical system much easier. In the world of website development, we call this a 
yFRPG.logicModels.codingPartTwo = . Much like a civil engineer must consider the efficacy of a roadway system, when building a website we must consider many aspects of the system, like cyber safety (allowing unsafe input data has led to many stolen identities and credit cards), user experience, and visual appeal. By better understanding the logical rules behind our software we better understand where this issues arise, preventing catastrophic database leaks and user rage-quits before they ever happen.
yFRPG.logicModels.goldbergDescription = it works perfectly 60% of the time!
yFRPG.logicModels.codeDesignPartOne = When designing software systems it's important to think it through from beginning to end. Most software bugs stem from coders thinking "it's not my job" or not putting that extra effort to consider edge cases because "it worked when I ran it". You must remember the 3 components of your logic model, so first consider your user 
yFRPG.logicModels.codeDesignPartTwo = . When navigating a site the user gives many inputs, like clicking a link, scrolling the page, logging in, or submitting a form.
yFRPG.logicModels.codeDesignPartThree = Next you must think about every step in your code, and how the 
yFRPG.logicModels.codeDesignPartFour = \ ultimately handle your users input and translates it into the program's 
yFRPG.logicModels.codeDesignPartFive = . Don't cut corners or leave problems for someone else to deal with. Building the best software you can the first time (you'll definitely write some messy code starting out, but after you make your first draft of something try to come back and look for ways to improve it) will save you a lot of time later on. Understand the deep inner workings of your 
yFRPG.logicModels.codeDesignPartSix = by toying around with it and asking questions!
yFRPG.logicModels.codeDesignPartSeven = The 
yFRPG.logicModels.codeDesignPartEight = \ is what the users of your software experience (this is a 
yFRPG.logicModels.codeDesignPartNine = critical
yFRPG.logicModels.codeDesignPartTen = \ aspect of your logic model), so when coding you must always think about what your users are trying to achieve, and not only all the possible issues and bugs they could run into, but also how to make your software straightforward and convenient. Like good road design, your software should effectively serve your users, instead of forcing your users to be focused on tediously tinkering with poorly designed software. Take responsibility as an engineer for avoidable crashes and other design issues that arise with your software.
```
Ultimately I think it would make much more sense for there just to be a single paragraph of text with the links injected afterwards or something (I'm not sure the best solution but there's one).

**Comment by nbouvrette** [comment]
Sorry for the late reply - we are working on a branch that will support what you're describing: https://github.com/Avansai/next-multilingual/tree/jsx-messages

Right now I am debugging issues with SSR markup when hosting on Vercel so until I am done fixing this, this branch is on hold but I will definitely keep you posted as this is a core feature we need on our end as well !

**Comment by nbouvrette** [comment]
@L1lith we just release `0.10.0` which supports this feature. Please give it a try and let us know what you think!

**Comment by L1lith** [comment]
> @L1lith we just released `0.10.0` which supports this feature. Please give it a try and let us know what you think!

I really appreciate you implementing this feature, this is awesome :) I currently have swapped to Gatsby for [this reason](https://github.com/vercel/next.js/discussions/18957). I would love to find the perfect solution for the internationalization of React apps for me, but I think there are a few issues holding this back. 

Here's some feedback if you're interested about the problems I have encountered.

1. I need static export (as linked above, not a fault of next-multilingual though)
2. Pages can have different layouts in different languages, letting us define multiple pages for each language of the same "canonical page" makes this really convenient [see here](https://github.com/L1lith/Your-First-RPG/tree/main/src/pages) 
3. I wish to develop my app in a specific language. Only having function calls and external JSON files to define my page content can make it super confusing to try to read through my app. [Here](https://github.com/L1lith/Your-First-RPG/blob/main/src/components/ShittyChecking.js) you can see one way I've solved this issue ```<span className={appTitle}>{useTranslation('💸 Banking', { es: '💸 Bancario' })}</span>``` As you can see the second argument could just as well be a external JSON file, not unlike how this library does translations, but by letting me provide the "default translation" (we provide a "default language" so we can infer which language this is) it makes developing the app much easier as I can actually read the content of what I'm developing in the page file.

Feel free to read through how I've implemented translations in my project, personally I've found it to be super useful, and any inspiration you could draw for this library I think would be a great thing for the community.

**Comment by nbouvrette** [comment]
Thanks for sharing your experience @L1lith - here are my thoughts

> I need static export (as linked above, not a fault of next-multilingual though)

I guess this is something Next.js could improve in the future - we currently don't have a need for this - just curious from your perspective, what is the benefit of using a framework like Next.js to export a static site rather than using a simpler solution like [WordPress](https://wordpress.com/)? WordPress also supports your second point by being able to manage content individually by language. There is also self-service content editing and other cool features that can be pretty useful when managing a site with more static content.

> Pages can have different layouts in different languages, letting us define multiple pages for each language of the same "canonical page" makes this really convenient see here

What kind of different layout do you have in mind? Typically if a canonical page is translated, layout changes would be minimal - for example you could have right-to-left language that changes the direction of the site but the layout would remain the same.

The challenge is you make too many changes to the layout, and then end up let's say with a Spanish layout that has additional components not used in English, this means that you would need to add the strings in English and translate them in Spanish which would make no sense if you pay someone to do this. In these cases, it actually means that this becomes "native language authoring" and no longer translation. Our solution is focusing on translation since this is the most complex part of i18n. If you have needs for native content I believe there are ways to do this in Next.js by adding extra logic and storing native strings in `.json` files for example, that would be out of scope for translation. The same would apply to language-specific "config" like video URLs for example - which of course would never be in scope for translation anyway.

> you can see one way I've solved this issue <span className={appTitle}>{useTranslation('💸 Banking', { es: '💸 Bancario' })}</span>

Very creative way but this will only work if the developer (in this case you hehe) can code and translate in all languages you need. Which of course for bigger projects, will no longer work - some aspects you might wanna consider:

- adding more languages (not sure how it would work with your solution)
- translating by non-technical people, even using LSP (language service providers) that will ask for you for translation files that contain no code - this is why we use `.properties` file here (more details in the [design decisions](https://github.com/Avansai/next-multilingual/blob/main/docs/design-decisions.md) docs).
- leveraging linguistic tools like translation memory to save on translation cost
- etc.

I don't know if you read our [design decisions](https://github.com/Avansai/next-multilingual/blob/main/docs/design-decisions.md) document but I would highly recommend it to you if you have a chance. With the little knowledge I saw on the repo you shared, I would probably not start refactoring everything if you can handle all the languages - it's probably fine for what you intend to do. I would even maybe challenge you to try WordPress :)

But there are a lot of good practices to keep in mind, especially when you start working on projects where you need to pay for translation!

**Comment by L1lith** [comment]
> adding more languages (not sure how it would work with your solution)
> translating by non-technical people, even using LSP (language service providers) that will ask for you for translation files that contain no code - this is why we use .properties file here (more details in the [design decisions](https://github.com/Avansai/next-multilingual/blob/main/docs/design-decisions.md) docs).

I don't think this is really an issue for the design pattern, my point was that you could do something like this
`messages.format('This is our header in the default language', 'headline')`
instead of 
`messages.format('headline')`
The benefit of this is that you can make the "default language" the language used by the development team, but you can also reference external files that non-developers can provide translations inside of. For me as a developer this is much more readible.
also you can add more languages, 'es' here refers to the spanish language but you could add more keys. This however is more of an implementation detail. My idea I was trying to get across is that you can let the devs write in their native language inside the IDE and still have translation support. Having to constantly refer between either the rendered page or the translation source files while editing the page is really disorienting IMO.
> I would even maybe challenge you to try WordPress :)
I appreciate the suggestion, I'm open to hearing more about why to do this but currently I don't want to use wordpress because using a coding framework seems to be more flexible, also wordpress from my understanding is generally very slow due to it's PHP base, and the plugins/themes can be very poorly optimized as well. Also I don't want to have to pay money for those services.

In your design doc
> Localization is abstracted from developers and can be easier to use in some cases.
I think for any dev teams that share a single common language, this would be a bad thing. We use the text content of the page to understand what we're looking at. I would imagine Netflix probably has a lot of developers speaking many different languages so for that that makes sense for them, but for a lot of smaller teams I would imagine it makes less sense

**Comment by nbouvrette** [comment]
> `messages.format('This is our header in the default language', 'headline')`
> instead of
> `messages.format('headline')`

In your example would `'This is our header in the default language'` be the actual English string or would it be used as some sort of description? Challenges I see if

- If this is the English string
  - How can you translate these strings since they live in the code? you would need some sort of export job?
- If this is a description
  - Then this means you will need to keep the `en` file in sync with the description 

But I agree with you, using keys can be challenging. Some solutions out there recommend that the actual key is the message. The problem with this is that you could end up with key collisions which would result in translation quality issues... so I would not recommend that. Maybe some sort of IDE plugin could be a better approach where you would be able to have auto-completion and preview of the keys... could be a cool feature :)

> I appreciate the suggestion, currently I don't want to use wordpress because using a coding framework seems to be more flexible, also wordpress from my understanding is generally very slow due to it's PHP base, and the plugins/themes can be very poorly optimized as well. Also I don't want to have to pay money for those services. With optimized SSG using Gatsby I can significantly reduce the amount of bloat.

You're right, a CMS will always be less flexible than coding your own app - but for static content, you can get something up and running very quickly so it's really a question of tradeoffs. PHP is not slow at all, this is probably a myth :) Optimizing for speed is often done for very specific goals, like SEO ranking or conversion for e-commerce sites when you have a lot of data.. but for static sites, in my opinion, you can use a lot of different solutions and performance will be very similar - there are even a lot of free CMS out there that could probably do the trick but I mostly have experience is with WordPress.

> I think for any dev teams that share a single common language, this would be a bad thing. We use the text content of the page to understand what we're looking at. I would imagine Netflix probably has a lot of developers speaking many different languages so for that that makes sense for them, but for a lot of smaller teams I would imagine it makes less sense

I'm not a fan of global string repositories but there are many solutions that offer that, like [Phrase](https://phrase.com/). I've seen different flavors the main drawback is it becomes really hard to track who uses what and also if it's used in the right context. As you can probably tell from our solution, we believe strings should be as close as possible as to where they are used and removed when no longer used. This just helps to keep everything clean. Keeping a codebase clean includes all assets!
