### ISSUE TITLE
SSG support ?

### ISSUE THREAD

**Issue by NielsvanHoof** [Avansai/next-multilingual#21]
Hey, we're considering stepping over from next-i18next to your package but one things seems a bit unclear regarding SSG support. is there any way to  use SSG on the home page instead of using SSR? our current data fetching method relays heavily on SSG and porting this over would take quite a bit of time.

Our main attraction is the ability to translate URLS

**Comment by nbouvrette** [comment]
Hi @NielsvanHoof - I just made a quick test using (advanced config from the readme)

```
  i18n: {
    locales: config.getUrlLocalePrefixes(),
    defaultLocale: config.getDefaultUrlLocalePrefix(),
    localeDetection: true,
  }
```

(Locale detection: **true** is the important part)

I also removed the SSR portion on the homepage and it looks like the redirect behavior from Next.js is back to normal.

We never tested this before because on our end we wanted to get rid of the redirection but maybe this is something we should add to the documentation!

**Comment by NielsvanHoof** [comment]
Hey, alright so the only thing that would have to be done is to just remove the SSR portion and keep my current SSG stuff? will see if it breaks any thing in regards to linking and stuff like that.

**Comment by nbouvrette** [comment]
@NielsvanHoof yes, the SSR snippets in the example were only there to support the dynamic homepage but you don't have to use it. SSG should work normally - we tested it in dynamic routes [here](https://github.com/Avansai/next-multilingual/blob/main/example/pages/dynamic-route-test/%5Bid%5D.tsx), and the localized URLs are working fine. 

I'll close the issue for now and if you find anything wrong, we can either re-open it or create a new one.
