### ISSUE TITLE
Localized URLs for dynamic pages?

### ISSUE THREAD

**Issue by ithrasil** [Avansai/next-multilingual#35]
How can I achieve given URL mapping? 

`/en-us/dynamic-urls/first` -> `/pl-pl/dynamiczne-urle/pierwszy` 
`/en-us/dynamic-urls/second` -> `/pl-pl/dynamiczne-urle/drugi` 
`/en-us/dynamic-urls/third` -> `/pl-pl/dynamiczne-urle/trzeci` 

Documentation describes only simple, numerical, dynamic page id case.

---

![image](https://user-images.githubusercontent.com/11476062/185192500-aad0720d-f3cb-4e45-9085-80f65eebbac9.png)
btw. link here doesn't work. From what I can see https://github.com/Avansai/next-multilingual/blob/main/example/pages/tests/dynamic-routes/%5Bid%5D.tsx this is the correct link

**Comment by nbouvrette** [comment]
Sorry, I just saw this, and thanks for reporting the broken link. I fixed this one and others in this commit https://github.com/Avansai/next-multilingual/commit/c9333dc7c548289a01ed6c61f90a849b2f6c1346.

Regarding dynamic routes, we provided a simple example that does not require translation because this problem can become really complex. Imagine if you have 2 or 3 different levels of dynamic routes, and how do you get the correct link on the language picker?

Also in general, Next.js can already do this part with its router. You could basically create a `first`, `second`, `third`, route loading the same component. So we thought that if you need to replicate Next.js' maybe it's not necessarily a pattern we wanted to spend too much time on solving.

Having said this, there could be valid use cases that could benefit SEO like: `/profiles/[city]/[page]` where `city` could be a like of hundreds of cities that you would predefine and localize, which obviously would be annoying to create as pages.

I think I have some ideas on how to get this to work... let me try a few things and circle back

**Comment by nbouvrette** [comment]
Thanks for pushing me to push this feature @ithrasil - it took me longer than I was expecting but it's also why I never did it before. Let me know if you have any feedback on this new capability or if you have suggestions on how to improve the documentation. You can try it out in `next-multilingual` >= `1.5.0`
