### ISSUE TITLE
country code in url

### ISSUE THREAD

**Issue by rootion** [Avansai/next-multilingual#9]
This package looks very promising. Is there a way to customize the url where instead of the locale (for example: `pt-BR`), we could use a country code (`pt`)?

Could be something like 
```
locales: [
  { 'nl': 'nl-NL' }, 
  { 'us': 'en-US' }, 
  { 'uk': 'en-GB'}, 
  { 'pt': 'pt-BT'}
]
```

**Comment by nbouvrette** [comment]
Thanks @rootion for being an early reviewer of our package.

Do only support country+language right now and we documented the reason in our [design decision](https://github.com/Avansai/next-multilingual/blob/main/docs/design-decisions.md) document. Basically:

BCP47 language tags consisting of both an ISO 639-1 alpha-2 language code and an ISO 3166-1 alpha-2 country code must be used at all times when setting up your next.config.js. Using a simple language code is not recommended because:
- There is no such concept as a "regionsless" variant of a language. Even English might seem like a simple language but there are many nuances between English U.S. and English U.K. By not specifying which variant is used, the content creator or the translator will have to decide and this can lead to inconsistency.
- On top of using different expressions, there are many other differences such as date, currency, or number formats. If a site is using none of these, it might sound acceptable to simply use a language code but there are few use cases where this would apply.
- SEO: by targeting better the language with a country, your results will be more relevant in the search results of those countries - Moz, 2021

One of the goals of our package is to enforce what we consider best practices. If you disagree with this decision we are happy to discuss it more with you.

**Comment by rootion** [comment]
Thank you for this answer.

Unfortunately this design decision limits the usage of this package if you have a certain url architecture. [Über](https://github.com/vercel/next.js/discussions/17078#discussioncomment-77915) and [apple.com](https://github.com/vercel/next.js/discussions/17078#discussioncomment-93339) in fact are following country and language code as a subpath:

https://www.apple.com/ca/fr

In our case in particular we are smaller than them ;) and we are looking to only have country code in the url. 
For our needs, /en/ or /uk/ are providing enough context and are easier to read than the entire locale name.

**Comment by nbouvrette** [comment]
You said you want only the country code but I think you meant only the language code?

My biggest concern with supporting this is that people think that the country code is not important when in fact it is, not only for the reasons mentioned in the design decision but also during the translation process. Of course for smaller businesses, it might be rare to have multiple variants of English but semantically you are using an English variant specific to a country, so our thought was to simply make it explicit.

Also when you mean easier to read, do you mean from a customer perspective who looks at the URL?

**Comment by nbouvrette** [comment]
I was just re-reading your original locale map, and it does look like you want to use country codes. Did you consider that there might be different languages used in these countries and also the impact on SEO? I would recommend sticking to standard language tags as defined in BCP47. If you create your own mapping you will break away from standards used across the entire translation process.

**Comment by nbouvrette** [comment]
I will close this issue for now since it seems to go against standards. Please respond back if you would like to continue the discussion or feel free to fork our repo to tailor it to your needs but I would still not recommend doing this!
